//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.11 at 10:42:38 PM CET 
//


package se.sysmaps.entities;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for artikel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="artikel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Namn" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Namn2" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Prisinklmoms" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Volymiml" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Saljstart" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Slutlev" type="{}empty"/>
 *         &lt;element name="Varugrupp" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Ursprung" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Ursprunglandnamn" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Producent" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="Argang" type="{}empty_or_year"/>
 *         &lt;element name="Provadargang" type="{}zero_or_year"/>
 *         &lt;element name="Alkoholhalt" type="{}percent"/>
 *         &lt;element name="nr" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Artikelid" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Varnummer" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="PrisPerLiter" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Forpackning" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Forslutning" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Leverantor" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Sortiment" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Ekologisk" type="{}zero_or_one"/>
 *         &lt;element name="Koscher" type="{}zero_or_one"/>
 *         &lt;element name="RavarorBeskrivning" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Pant" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "artikel", propOrder = {
    "namn",
    "namn2",
    "prisinklmoms",
    "volymiml",
    "saljstart",
    "slutlev",
    "varugrupp",
    "ursprung",
    "ursprunglandnamn",
    "producent",
    "argang",
    "provadargang",
    "alkoholhalt",
    "nr",
    "artikelid",
    "varnummer",
    "prisPerLiter",
    "forpackning",
    "forslutning",
    "leverantor",
    "sortiment",
    "ekologisk",
    "koscher",
    "ravarorBeskrivning",
    "pant"
})
public class Artikel {

    @XmlElement(name = "Namn", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String namn;
    @XmlElement(name = "Namn2", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String namn2;
    @XmlElement(name = "Prisinklmoms", required = true)
    protected BigDecimal prisinklmoms;
    @XmlElement(name = "Volymiml", required = true)
    protected String volymiml;
    @XmlElement(name = "Saljstart", required = true)
    @XmlSchemaType(name = "date")
    protected Date saljstart;
    @XmlElement(name = "Slutlev", required = true)
    protected String slutlev;
    @XmlElement(name = "Varugrupp", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String varugrupp;
    @XmlElement(name = "Ursprung", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String ursprung;
    @XmlElement(name = "Ursprunglandnamn", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String ursprunglandnamn;
    @XmlElement(name = "Producent")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String producent;
    @XmlElement(name = "Argang", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String argang;
    @XmlElement(name = "Provadargang", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String provadargang;
    @XmlElement(name = "Alkoholhalt", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String alkoholhalt;
    @Id
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger nr;
    @XmlElement(name = "Artikelid", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger artikelid;
    @XmlElement(name = "Varnummer", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger varnummer;
    @XmlElement(name = "PrisPerLiter", required = true)
    protected BigDecimal prisPerLiter;
    @XmlElement(name = "Forpackning", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String forpackning;
    @XmlElement(name = "Forslutning", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String forslutning;
    @XmlElement(name = "Leverantor", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String leverantor;
    @XmlElement(name = "Sortiment", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String sortiment;
    @XmlElement(name = "Ekologisk", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ekologisk;
    @XmlElement(name = "Koscher", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String koscher;
    @XmlElement(name = "RavarorBeskrivning", required = true)
    protected String ravarorBeskrivning;
    @XmlElement(name = "Pant", required = true)
    protected BigDecimal pant;

    /**
     * Gets the value of the namn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamn() {
        return namn;
    }

    /**
     * Sets the value of the namn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamn(String value) {
        this.namn = value;
    }

    /**
     * Gets the value of the namn2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamn2() {
        return namn2;
    }

    /**
     * Sets the value of the namn2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamn2(String value) {
        this.namn2 = value;
    }

    /**
     * Gets the value of the prisinklmoms property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrisinklmoms() {
        return prisinklmoms;
    }

    /**
     * Sets the value of the prisinklmoms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrisinklmoms(BigDecimal value) {
        this.prisinklmoms = value;
    }

    /**
     * Gets the value of the volymiml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolymiml() {
        return volymiml;
    }

    /**
     * Sets the value of the volymiml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolymiml(String value) {
        this.volymiml = value;
    }

    /**
     * Gets the value of the saljstart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getSaljstart() {
        return saljstart;
    }

    /**
     * Sets the value of the saljstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSaljstart(Date value) {
        this.saljstart = value;
    }

    /**
     * Gets the value of the slutlev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlutlev() {
        return slutlev;
    }

    /**
     * Sets the value of the slutlev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlutlev(String value) {
        this.slutlev = value;
    }

    /**
     * Gets the value of the varugrupp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarugrupp() {
        return varugrupp;
    }

    /**
     * Sets the value of the varugrupp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarugrupp(String value) {
        this.varugrupp = value;
    }

    /**
     * Gets the value of the ursprung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrsprung() {
        return ursprung;
    }

    /**
     * Sets the value of the ursprung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrsprung(String value) {
        this.ursprung = value;
    }

    /**
     * Gets the value of the ursprunglandnamn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrsprunglandnamn() {
        return ursprunglandnamn;
    }

    /**
     * Sets the value of the ursprunglandnamn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrsprunglandnamn(String value) {
        this.ursprunglandnamn = value;
    }

    /**
     * Gets the value of the producent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducent() {
        return producent;
    }

    /**
     * Sets the value of the producent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducent(String value) {
        this.producent = value;
    }

    /**
     * Gets the value of the argang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArgang() {
        return argang;
    }

    /**
     * Sets the value of the argang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArgang(String value) {
        this.argang = value;
    }

    /**
     * Gets the value of the provadargang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvadargang() {
        return provadargang;
    }

    /**
     * Sets the value of the provadargang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvadargang(String value) {
        this.provadargang = value;
    }

    /**
     * Gets the value of the alkoholhalt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlkoholhalt() {
        return alkoholhalt;
    }

    /**
     * Sets the value of the alkoholhalt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlkoholhalt(String value) {
        this.alkoholhalt = value;
    }

    /**
     * Gets the value of the nr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNr() {
        return nr;
    }

    /**
     * Sets the value of the nr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNr(BigInteger value) {
        this.nr = value;
    }

    /**
     * Gets the value of the artikelid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArtikelid() {
        return artikelid;
    }

    /**
     * Sets the value of the artikelid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArtikelid(BigInteger value) {
        this.artikelid = value;
    }

    /**
     * Gets the value of the varnummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVarnummer() {
        return varnummer;
    }

    /**
     * Sets the value of the varnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVarnummer(BigInteger value) {
        this.varnummer = value;
    }

    /**
     * Gets the value of the prisPerLiter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrisPerLiter() {
        return prisPerLiter;
    }

    /**
     * Sets the value of the prisPerLiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrisPerLiter(BigDecimal value) {
        this.prisPerLiter = value;
    }

    /**
     * Gets the value of the forpackning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForpackning() {
        return forpackning;
    }

    /**
     * Sets the value of the forpackning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForpackning(String value) {
        this.forpackning = value;
    }

    /**
     * Gets the value of the forslutning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForslutning() {
        return forslutning;
    }

    /**
     * Sets the value of the forslutning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForslutning(String value) {
        this.forslutning = value;
    }

    /**
     * Gets the value of the leverantor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeverantor() {
        return leverantor;
    }

    /**
     * Sets the value of the leverantor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeverantor(String value) {
        this.leverantor = value;
    }

    /**
     * Gets the value of the sortiment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortiment() {
        return sortiment;
    }

    /**
     * Sets the value of the sortiment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortiment(String value) {
        this.sortiment = value;
    }

    /**
     * Gets the value of the ekologisk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEkologisk() {
        return ekologisk;
    }

    /**
     * Sets the value of the ekologisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEkologisk(String value) {
        this.ekologisk = value;
    }

    /**
     * Gets the value of the koscher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKoscher() {
        return koscher;
    }

    /**
     * Sets the value of the koscher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKoscher(String value) {
        this.koscher = value;
    }

    /**
     * Gets the value of the ravarorBeskrivning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRavarorBeskrivning() {
        return ravarorBeskrivning;
    }

    /**
     * Sets the value of the ravarorBeskrivning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRavarorBeskrivning(String value) {
        this.ravarorBeskrivning = value;
    }

    /**
     * Gets the value of the pant property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPant() {
        return pant;
    }

    /**
     * Sets the value of the pant property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPant(BigDecimal value) {
        this.pant = value;
    }

}
